
language: cpp
dist: trusty

matrix:
  exclude:
  - os: linux
    compiler: clang

addons:
  apt:
    packages:
      - clang-3.9
      - libxml2-dev
      - libpng12-dev
      - libjpeg-dev
      - libjpeg-turbo8
      - libsdl2-dev
      - libfreetype6-dev
      - libsigc++-2.0-dev

before_script:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install freetype libsigc++; fi
  - git clone https://github.com/geekprojects/libgeek.git; cd libgeek; ./autogen.sh; ./configure; make; if [$TRAVIS_OS_NAME == osx]; then make install; else sudo make install; fi; cd -
  - ./autogen.sh --verbose 
  - ./configure

script: make

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

