---

language: cpp
dist: bionic
arch:
  - amd64
  - arm64

matrix:
  exclude:
    - os: linux
      compiler: clang
    - os: osx
      arch: arm64

addons:
  apt:
    packages:
      - libxml2-dev
      - libpng-dev
      - libjpeg-dev
      - libjpeg-turbo8
      - libsdl2-dev
      - libfreetype6-dev
      - libsigc++-2.0-dev
      - uuid-dev
      - freeglut3-dev
  homebrew:
    packages:
      - freetype
      - libsigc++@2
      - libtool
      - antlr@4
      - antlr4-cpp-runtime
    update: true
  sonarcloud:
    organization: "geekprojects"
    token:
      secure: "b/qu2nlAHQtlZ/rcy54Z5BvYzxN0C26c2HL3M/hdNXVTOnsje/nimd9duk202eU5ZdBYUsblZSqNrMOVZdCYhAqwzwZ/KZZEevHcvLI96dmMiH+k85lwEslZyCscHK2qRx2fXjMkdT1zw00XDAzLUb+5XTKQjfyg/7mwKzWZIzpOhf6u3SkzXGz1DQLwH5/TmrnWg5YheARKGMg3A709gU6O+ZCR3Won5mPfjMyUXrpsY1WgiWVsb/SOcQTyZC5MRuM/0BwbNM9CpA5eCW0bJ+yOi7weFIvLLtM16+2amJequNPAHY1+3JSTASPn7juQD4Bj0OaCCgAyyaaDQopYsq3T7zv51PVA//sFtkHbMGGwkzTgn9XCjXirylJNsQQKTr54Os7mlqN+SN5uCLcL+EJaPKajc8EmhBGFzgGOfD2qURWukc1dHw5U66LuW8OZAm4AMcpuBA5rrYCF0ebQFmwhlJ6aznM3HJhEqXFHIfXS90uLiYhooQaJz6hRvLfGVbzSuKdyxPoXJSUtHUerpQ5ulaYj2Bcq4H0+suusmIyPG84FpiRCISx0PJ3n0byVm5a59fglKBSupOfGUrFDyRvyZs0KDJPYOKeFYb4Nnlx+BD+sIZLE9ykHp7JhUy7fYRVgINgts2yachS+wGXRf7Cdu3Hd+C8BEEWIQXWHc78="

install:
  - git clone https://github.com/geekprojects/libgeek.git; cd libgeek; mkdir build; cd build; cmake ..; make; if [ "$TRAVIS_OS_NAME" == "osx" ]; then make install; else sudo make install; sudo ldconfig; fi; cd -
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then git clone https://github.com/antlr/antlr4.git; mkdir antlr4/runtime/Cpp/build; cd antlr4/runtime/Cpp/build; cmake ..; make; sudo make install; sudo ldconfig; cd -; fi

before_script:
  - mkdir build; cmake ..

script:
  - build-wrapper-linux-x86-64 --out-dir bw-output make
# && make test
  - sonar-scanner

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

#cache:
#  directories:
#    - '$HOME/.sonar/cache'

