---

language: cpp
dist: xenial

matrix:
  exclude:
    - os: linux
      compiler: clang

addons:
  apt:
    packages:
      - libxml2-dev
      - libpng12-dev
      - libjpeg-dev
      - libjpeg-turbo8
      - libsdl2-dev
      - libfreetype6-dev
      - libsigc++-2.0-dev
  homebrew:
    packages:
      - freetype
      - libsigc++
      - libtool
    update: true

before_script:
  - git clone https://github.com/geekprojects/libgeek.git; cd libgeek; ./autogen.sh; ./configure; make; if [$TRAVIS_OS_NAME == osx]; then make install; else sudo make install; sudo ldconfig; fi; cd -
  - ./autogen.sh --verbose
  - ./configure --enable-tests

script:
  - make
  - make test

compiler:
  - clang
  - gcc

os:
  - linux
  - osx
