
language: cpp
dist: trusty

addons:
  apt:
    packages:
      - libxml2-dev
      - libpng12-dev
      - libjpeg-dev
      - libjpeg-turbo8
      - libsdl2-dev

before_script:
  - git clone https://github.com/geekprojects/libgeek.git; cd libgeek; ./autogen.sh; ./configure; make && make install; cd -
  - ./autogen.sh --verbose 
  - ./configure

script: make && make test

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

